package com.tw;

import java.util.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    //保存全部学生信息
    public Map<String,Student> studentMap = new HashMap<>();

    public boolean someLibraryMethod() {
        return true;
    }

    //添加学生信息
    public void addStudentInfo(){
        System.out.println("请输入学生信息（格式：姓名, 学号, 学科: 成绩, ...），按回车提交：");
        Scanner sc = new Scanner(System.in);
        //处理输入信息，使用try..catch处理异常输入
        while (true) {
            try {
                String[] studentInfo = sc.nextLine().split(",|，");
                Student student = new Student(studentInfo[0], studentInfo[1]);
                double totalScore = 0.0;
                for (int i = 2; i < studentInfo.length; i++) {
                    String subject = studentInfo[i].split(":|：")[0];
                    Double score = Double.valueOf(studentInfo[i].split(":|：")[1]);
                    student.setStudentScore(subject, score);
                    totalScore += score;
                }
                student.setStudentScore("平均分",totalScore/(studentInfo.length-2));
                student.setStudentScore("总分",totalScore);
                studentMap.put(student.getStudentId(), student);
                System.out.println("学生" + student.getStudentName() + "的成绩被添加");
                break;
            } catch (Exception e) {
                System.out.println("请按正确的格式输入（格式：姓名, 学号, 学科: 成绩, ...）：");
            }
        }
    }

    //按学号查询学生信息
    public void getStudentScore(){
        System.out.println("请输入要打印的学生的学号（格式： 学号, 学号,...），按回车提交：");
        Scanner sc = new Scanner(System.in);
        try{
            String[] studentIds = sc.nextLine().split(",|，");
            System.out.println("成绩单");
            System.out.println("姓名|数学|语文|英语|编程|平均分|总分");
            System.out.println("=======================================");
            //输出每个要查询的学生信息
            for (String studentId : studentIds) {
                Student student = studentMap.get(studentId);
                System.out.print(student.getStudentName()+"|");
                System.out.println(student.studentScore.get("数学")+"|"+student.studentScore.get("语文")+"|"+
                        student.studentScore.get("英语")+"|"+student.studentScore.get("编程")+"|"+
                        student.studentScore.get("平均分")+"|"+student.studentScore.get("总分"));
            }
            System.out.println("=======================================");
            System.out.println("全班总分平均数："+this.getAverageOfAllStudent());
            System.out.println("全班总分中位数："+this.getMedianOfAllStudent());
//            for (String studentId : studentIds) {
//                Student student = studentMap.get(studentId);
//                System.out.print(student.getStudentName());
////                double totalScore = 0.0;
//                for (String subject : student.studentScore.keySet()) {
//                    System.out.print("|"+student.studentScore.get(subject));
////                    totalScore += student.studentScore.get(subject);
//                }
//                System.out.println();
//                //输出总分和平均分
////                System.out.println(totalScore+"|"+totalScore/student.studentScore.size());
//            }
        }
        catch (Exception e){
                //输入的学号不存在，该学号在计算时就会被忽略。（不做处理）
        }
    }

    //全班总分中位数
    public double getMedianOfAllStudent(){
        double medianScore = 0.0;

        List<Double> totalScoreList = new ArrayList<>();
        for (String studentId : this.studentMap.keySet()) {
            Student student = this.studentMap.get(studentId);
            totalScoreList.add(student.studentScore.get("总分"));
        }
        Collections.sort(totalScoreList);
        //计算中位数
        int medianIndex = this.studentMap.size()/2;
        if(this.studentMap.size()%2 == 0){
            medianScore = (totalScoreList.get(medianIndex-1)+totalScoreList.get(medianIndex))/2.0;
        }
        else {
            medianScore = totalScoreList.get(medianIndex);
        }
        return medianScore;
    }

    //全班总分平均数
    public double getAverageOfAllStudent(){
        double averageScore = 0.0;
        double totalScore = 0.0;
        for (String studentId : this.studentMap.keySet()) {
            Student student = this.studentMap.get(studentId);
            totalScore += student.studentScore.get("总分");
        }
        averageScore = totalScore/this.studentMap.keySet().size();
        return averageScore;
    }

    public static void main(String[] args){
        Library library = new Library();
        while (true) {
            System.out.println("1.添加学生");
            System.out.println("2.生成成绩单");
            System.out.println("3.退出 请输入你的选择（1-3）：");

            try{
                Scanner sc = new Scanner(System.in);
                int command = sc.nextInt();
                if (command == 1) {
                    sc.skip("\n");
                    library.addStudentInfo();
                } else if (command == 2) {
                    sc.skip("\n");
                    library.getStudentScore();
                } else if (command == 3) {
                    sc.skip("\n");
                    System.exit(0);
                }
            }
            catch (Exception e){
                e.printStackTrace();
            }
        }
    }
}
